const servicedata = {
 
  Brakes: [
    {
      name: "Front Brake Pads",
      description: "Opening & Fitting of Front Brake Pads",
      description1: "Applicable for Set of 2 Front Brake Pads",
      description2: "Front Brake Disc Cleaning",
      description3: "Front Brake Pads Replacement (GoMechanic)",
      description4: "Inspection of Front Brake Calipers",
      description5: "Inspection of Front Brake Calipers",
      description6: "Inspection of Front Brake Calipers",
      image: "/servicesimage/brake/front.jpg",
      countInStock: 20,
      service_price: 64.0,
      weeks_to_arrive: 7,
      car_price: new carsDefaultPrice(),
    },
    {
      name: "Rear Brake Shoes",
      description: "1 Month Warranty on Fitting",
      description1: "Opening & Fitting of Front Brake Pads",
      description2: "Front Brake Pads Replacement",
      description3: "Applicable for Set of 2 Front Brake Pads",
      description4: "Inspection of Front Brake Calipers",
      description5: "Front Brake Disc Cleaning",
      image: "/servicesimage/brake/front.jpg",
      countInStock: 20,
      service_price: 64.0,
      weeks_to_arrive: 7,
      car_price: new carsDefaultPrice(),
    },
    {
      name: "Front Brake Pads",
      description: "1 Month Warranty on Fitting",
      description1: "Opening & Fitting of Front Brake Pads",
      description2: "Front Brake Pads Replacement",
      description3: "Applicable for Set of 2 Front Brake Pads",
      description4: "Inspection of Front Brake Calipers",
      description5: "Front Brake Disc Cleaning",
      image: "/servicesimage/brake/front.jpg",
      countInStock: 20,
      service_price: 64.0,
      weeks_to_arrive: 7,
      car_price: new carsDefaultPrice(),
    },
    {
      name: "Front Brake Pads",
      description: "1 Month Warranty on Fitting",
      description1: "Opening & Fitting of Front Brake Pads",
      description2: "Front Brake Pads Replacement",
      description3: "Applicable for Set of 2 Front Brake Pads",
      description4: "Inspection of Front Brake Calipers",
      description5: "Front Brake Disc Cleaning",
      image: "/servicesimage/brake/front.jpg",
      countInStock: 20,
      service_price: 64.0,
      weeks_to_arrive: 7,
      car_price: new carsDefaultPrice(),
    },
    {
      name: "Front Brake Pads",
      description: "1 Month Warranty on Fitting",
      description1: "Opening & Fitting of Front Brake Pads",
      description2: "Front Brake Pads Replacement",
      description3: "Applicable for Set of 2 Front Brake Pads",
      description4: "Inspection of Front Brake Calipers",
      description5: "Front Brake Disc Cleaning",
      image: "/servicesimage/brake/front.jpg",
      countInStock: 20,
      service_price: 64.0,
      weeks_to_arrive: 7,
      car_price: new carsDefaultPrice(),
    },
    {
      name: "Front Brake Pads",
      description: "1 Month Warranty on Fitting",
      description1: "Opening & Fitting of Front Brake Pads",
      description2: "Front Brake Pads Replacement",
      description3: "Applicable for Set of 2 Front Brake Pads",
      description4: "Inspection of Front Brake Calipers",
      description5: "Front Brake Disc Cleaning",
      image: "/servicesimage/brake/front.jpg",
      countInStock: 20,
      service_price: 64.0,
      weeks_to_arrive: 7,
      car_price: new carsDefaultPrice(),
    },
    {
      name: "Front Brake Pads",
      description: "1 Month Warranty on Fitting",
      description1: "Opening & Fitting of Front Brake Pads",
      description2: "Front Brake Pads Replacement",
      description3: "Applicable for Set of 2 Front Brake Pads",
      description4: "Inspection of Front Brake Calipers",
      description5: "Front Brake Disc Cleaning",
      image: "/servicesimage/brake/front.jpg",
      countInStock: 20,
      service_price: 64.0,
      weeks_to_arrive: 7,
      car_price: new carsDefaultPrice(),
    },
    {
      name: "Front Brake Pads",
      description: "1 Month Warranty on Fitting",
      description1: "Opening & Fitting of Front Brake Pads",
      description2: "Front Brake Pads Replacement",
      description3: "Applicable for Set of 2 Front Brake Pads",
      description4: "Inspection of Front Brake Calipers",
      description5: "Front Brake Disc Cleaning",
      image: "/servicesimage/brake/front.jpg",
      countInStock: 20,
      service_price: 64.0,
      weeks_to_arrive: 7,
      car_price: new carsDefaultPrice(),
    },
  ],

  ACFitments: [
    {
      name: "Cooling Coil Replacement",
      description: "Opening & Fitting of Front Brake Pads",
      description1: "Applicable for Set of 2 Front Brake Pads",
      description2: "Front Brake Disc Cleaning",
      description3: "Front Brake Pads Replacement (GoMechanic)",
      description4: "Inspection of Front Brake Calipers",
      description5: "Inspection of Front Brake Calipers",
      description6: "Inspection of Front Brake Calipers",
      image: "/servicesimage/brake/front.jpg",
      countInStock: 20,
      service_price: 64.0,
      weeks_to_arrive: 7,
      car_price: new carsDefaultPrice(),
    },
    {
      name: "Rear Brake Shoes",
      description: "1 Month Warranty on Fitting",
      description1: "Opening & Fitting of Front Brake Pads",
      description2: "Front Brake Pads Replacement",
      description3: "Applicable for Set of 2 Front Brake Pads",
      description4: "Inspection of Front Brake Calipers",
      description5: "Front Brake Disc Cleaning",
      image: "/servicesimage/brake/front.jpg",
      countInStock: 20,
      service_price: 64.0,
      weeks_to_arrive: 7,
      car_price: new carsDefaultPrice(),
    },
    {
      name: "Front Brake Pads",
      description: "1 Month Warranty on Fitting",
      description1: "Opening & Fitting of Front Brake Pads",
      description2: "Front Brake Pads Replacement",
      description3: "Applicable for Set of 2 Front Brake Pads",
      description4: "Inspection of Front Brake Calipers",
      description5: "Front Brake Disc Cleaning",
      image: "/servicesimage/brake/front.jpg",
      countInStock: 20,
      service_price: 64.0,
      weeks_to_arrive: 7,
      car_price: new carsDefaultPrice(),
    },
    {
      name: "Front Brake Pads",
      description: "1 Month Warranty on Fitting",
      description1: "Opening & Fitting of Front Brake Pads",
      description2: "Front Brake Pads Replacement",
      description3: "Applicable for Set of 2 Front Brake Pads",
      description4: "Inspection of Front Brake Calipers",
      description5: "Front Brake Disc Cleaning",
      image: "/servicesimage/brake/front.jpg",
      countInStock: 20,
      service_price: 64.0,
      weeks_to_arrive: 7,
      car_price: new carsDefaultPrice(),
    },
    {
      name: "Front Brake Pads",
      description: "1 Month Warranty on Fitting",
      description1: "Opening & Fitting of Front Brake Pads",
      description2: "Front Brake Pads Replacement",
      description3: "Applicable for Set of 2 Front Brake Pads",
      description4: "Inspection of Front Brake Calipers",
      description5: "Front Brake Disc Cleaning",
      image: "/servicesimage/brake/front.jpg",
      countInStock: 20,
      service_price: 64.0,
      weeks_to_arrive: 7,
      car_price: new carsDefaultPrice(),
    },
    {
      name: "Front Brake Pads",
      description: "1 Month Warranty on Fitting",
      description1: "Opening & Fitting of Front Brake Pads",
      description2: "Front Brake Pads Replacement",
      description3: "Applicable for Set of 2 Front Brake Pads",
      description4: "Inspection of Front Brake Calipers",
      description5: "Front Brake Disc Cleaning",
      image: "/servicesimage/brake/front.jpg",
      countInStock: 20,
      service_price: 64.0,
      weeks_to_arrive: 7,
      car_price: new carsDefaultPrice(),
    },
    {
      name: "Front Brake Pads",
      description: "1 Month Warranty on Fitting",
      description1: "Opening & Fitting of Front Brake Pads",
      description2: "Front Brake Pads Replacement",
      description3: "Applicable for Set of 2 Front Brake Pads",
      description4: "Inspection of Front Brake Calipers",
      description5: "Front Brake Disc Cleaning",
      image: "/servicesimage/brake/front.jpg",
      countInStock: 20,
      service_price: 64.0,
      weeks_to_arrive: 7,
      car_price: new carsDefaultPrice(),
    },
    {
      name: "Front Brake Pads",
      description: "1 Month Warranty on Fitting",
      description1: "Opening & Fitting of Front Brake Pads",
      description2: "Front Brake Pads Replacement",
      description3: "Applicable for Set of 2 Front Brake Pads",
      description4: "Inspection of Front Brake Calipers",
      description5: "Front Brake Disc Cleaning",
      image: "/servicesimage/brake/front.jpg",
      countInStock: 20,
      service_price: 64.0,
      weeks_to_arrive: 7,
      car_price: new carsDefaultPrice(),
    },
  ],

  
};
