const servicedata = {
  services: [
    {
      name: "Front bumper Paint",
      description: "2 Years Warranty on Paint",
      description1: "Grade A Primer",
      description2: "4 Layers of Painting",
      description3: "Premium DuPont Paint",
      description4: "Panel Rubbing Polishing",
      description5: "4 Layers of Painting",
      image: "/servicesimage/denting_penting/1.png",
      countInStock: 20,
    },
    {
      name: "Bonnet Paint",
      description: "2 Years Warranty on Paint",
      description1: "Grade A Primer",
      description2: "4 Layers of Painting",
      description3: "Premium DuPont Paint",
      description4: "Panel Rubbing Polishing",
      description5: "4 Layers of Painting",
      image: "/servicesimage/denting_penting/2.png",
      countInStock: 20,
    },
    {
      name: "Rear Bumper Paint",
      description: "2 Years Warranty on Paint",
      description1: "Grade A Primer",
      description2: "4 Layers of Painting",
      description3: "Premium DuPont Paint",
      description4: "Panel Rubbing Polishing",
      description5: "4 Layers of Painting",
      image: "/servicesimage/denting_penting/3.png",
      countInStock: 20,
    },
    {
      name: "Right Fender Pent",
      description: "2 Years Warranty on Paint",
      description1: "Grade A Primer",
      description2: "4 Layers of Painting",
      description3: "Premium DuPont Paint",
      description4: "Panel Rubbing Polishing",
      description5: "4 Layers of Painting",
      image: "/servicesimage/denting_penting/4.png",
      countInStock: 20,
    },
    {
      name: "Left Fender Pent",
      description: "2 Years Warranty on Paint",
      description1: "Grade A Primer",
      description2: "4 Layers of Painting",
      description3: "Premium DuPont Paint",
      description4: "Panel Rubbing Polishing",
      description5: "4 Layers of Painting",
      image: "/servicesimage/denting_penting/5.png",
      countInStock: 20,
    },
    {
      name: "Front Door (L)",
      description: "2 Years Warranty on Paint",
      description1: "Grade A Primer",
      description2: "4 Layers of Painting",
      description3: "Premium DuPont Paint",
      description4: "Panel Rubbing Polishing",
      description5: "4 Layers of Painting",
      image: "/servicesimage/denting_penting/6.png",
      countInStock: 20,
    },
    {
      name: "Front Door (R)",
      description: "2 Years Warranty on Paint",
      description1: "Grade A Primer",
      description2: "4 Layers of Painting",
      description3: "Premium DuPont Paint",
      description4: "Panel Rubbing Polishing",
      description5: "4 Layers of Painting",
      image: "/servicesimage/denting_penting/7.png",
    },
    {
      name: "Running Board (L)",
      description: "2 Years Warranty on Paint",
      description1: "Grade A Primer",
      description2: "4 Layers of Painting",
      description3: "Premium DuPont Paint",
      description4: "Panel Rubbing Polishing",
      description5: "4 Layers of Painting",
      image: "/servicesimage/denting_penting/1.png",
    },
    {
      name: "Trunk",
      description: "2 Years Warranty on Paint",
      description1: "Grade A Primer",
      description2: "4 Layers of Painting",
      description3: "Premium DuPont Paint",
      description4: "Panel Rubbing Polishing",
      description5: "4 Layers of Painting",
      image: "/servicesimage/denting_penting/1.png",
      countInStock: 20,
    },
    {
      name: "Quarter Panel (L)",
      description: "2 Years Warranty on Paint",
      description1: "Grade A Primer",
      description2: "4 Layers of Painting",
      description3: "Premium DuPont Paint",
      description4: "Panel Rubbing Polishing",
      description5: "4 Layers of Painting",
      image: "/servicesimage/denting_penting/1.png",
      countInStock: 20,
    },
    {
      name: "Quarter Panel (R)",
      description: "2 Years Warranty on Paint",
      description1: "Grade A Primer",
      description2: "4 Layers of Painting",
      description3: "Premium DuPont Paint",
      description4: "Panel Rubbing Polishing",
      description5: "4 Layers of Painting",
      image: "/servicesimage/denting_penting/1.png",
      countInStock: 20,
    },
    {
      name: "Running Board (R)",
      description: "2 Years Warranty on Paint",
      description1: "Grade A Primer",
      description2: "4 Layers of Painting",
      description3: "Premium DuPont Paint",
      description4: "Panel Rubbing Polishing",
      description5: "4 Layers of Painting",
      image: "/servicesimage/denting_penting/1.png",
      countInStock: 20,
    },
    {
      name: "Roof",
      description: "2 Years Warranty on Paint",
      description1: "Grade A Primer",
      description2: "4 Layers of Painting",
      description3: "Premium DuPont Paint",
      description4: "Panel Rubbing Polishing",
      description5: "4 Layers of Painting",
      image: "/servicesimage/denting_penting/1.png",
      countInStock: 20,
    },
  ],

  headlights: [
    {
      name: "Front Headlight",
      description: "1 Month Warranty on Fitting",
      description1: "For Broken / Cracked Lights (Recommended)",
      description2: "Headlight OES (Price for single unit)",
      description3: "Free Pickup & Drop",
      description4: "Opening & Fitting of Bumper/Headlight",
      description5: "Projector/LEDs/DRLs Additional (If Applicable)",
      image: "/servicesimage/headlight/front-light.jpg",
      countInStock: 20,
    },
    {
      name: "Rear Taillight",
      description: "1 Month Warranty on Fitting",
      description1: "For Broken / Cracked Lights (Recommended)",
      description2: "Headlight OES (Price for single unit)",
      description3: "Free Pickup & Drop",
      description4: "Opening & Fitting of Bumper/Headlight",
      description5: "Projector/LEDs/DRLs Additional (If Applicable)",
      image: "/servicesimage/headlight/rear-light.jpg",
      countInStock: 20,
    },
    {
      name: "Fog Light",
      description: "1 Month Warranty on Fitting",
      description1: "For Broken / Cracked Lights (Recommended)",
      description2: "Headlight OES (Price for single unit)",
      description3: "Free Pickup & Drop",
      description4: "Opening & Fitting of Bumper/Headlight",
      description5: "Projector/LEDs/DRLs Additional (If Applicable)",
      image: "/servicesimage/headlight/fog-light.jpg",
      countInStock: 20,
    },
  ],

  periodics: [
    {
      name: "Basic Service",
      hour: "Take 3 Hours",
      warranty: "2 Months Warranty",
      month: "Every 5,000 Kms / 3 Months",
      included:
        "-Heater/Spark Plugs, -Engine Oil, Oil Filter, Wiper Fluid Coolant (200 ml), Battery Water (500 ml",
      other: "Health Reporting -Dashboard Polishing -Tyre Polishing",
      image: "/servicesimage/periodic/basic.jpg",
      countInStock: 20,
    },
    {
      name: "Advance Service",
      hour: "Take 3 Hours",
      warranty: "2 Months Warranty",
      month: "Every 5,000 Kms / 3 Months",
      included:
      "-Heater/Spark Plugs, -Engine Oil, Oil Filter, Wiper Fluid Coolant (200 ml), Battery Water (500 ml",
      other: "Health Reporting -Dashboard Polishing -Tyre Polishing",
      image: "/servicesimage/periodic/advanced.jpg",
      countInStock: 20,
    },
    {
      name: "Premium Service",
      hour: "Take 3 Hours",
      warranty: "2 Months Warranty",
      month: "Every 5,000 Kms / 3 Months",
      included:
        "-Heater/Spark Plugs, -Engine Oil, Oil Filter, Wiper Fluid Coolant (200 ml), Battery Water (500 ml",
      other: "Health Reporting -Dashboard Polishing -Tyre Polishing",
      image: "/servicesimage/periodic/primeium.jpg",
      countInStock: 20,
    },
  ],

  Brakes: [
    {
      name: "Front Brake Pads",
      description: "1 Month Warranty on Fitting",
      description1: "For Broken / Cracked Lights (Recommended)",
      description2: "Headlight OES (Price for single unit)",
      description3: "Free Pickup & Drop",
      description4: "Opening & Fitting of Bumper/Headlight",
      description5: "Projector/LEDs/DRLs Additional (If Applicable)",
      image: "/servicesimage/brake/front.jpg",
      countInStock: 20,
    },
    {
      name: "Front Brake Pads",
      description: "1 Month Warranty on Fitting",
      description1: "For Broken / Cracked Lights (Recommended)",
      description2: "Headlight OES (Price for single unit)",
      description3: "Free Pickup & Drop",
      description4: "Opening & Fitting of Bumper/Headlight",
      description5: "Projector/LEDs/DRLs Additional (If Applicable)",
      image: "/servicesimage/brake/front.jpg",
      countInStock: 20,
    },
    {
      name: "Front Brake Pads",
      description: "1 Month Warranty on Fitting",
      description1: "For Broken / Cracked Lights (Recommended)",
      description2: "Headlight OES (Price for single unit)",
      description3: "Free Pickup & Drop",
      description4: "Opening & Fitting of Bumper/Headlight",
      description5: "Projector/LEDs/DRLs Additional (If Applicable)",
      image: "/servicesimage/brake/front.jpg",
      countInStock: 20,
    },
    {
      name: "Front Brake Pads",
      description: "1 Month Warranty on Fitting",
      description1: "For Broken / Cracked Lights (Recommended)",
      description2: "Headlight OES (Price for single unit)",
      description3: "Free Pickup & Drop",
      description4: "Opening & Fitting of Bumper/Headlight",
      description5: "Projector/LEDs/DRLs Additional (If Applicable)",
      image: "/servicesimage/brake/front.jpg",
      countInStock: 20,
    },
    {
      name: "Front Brake Pads",
      description: "1 Month Warranty on Fitting",
      description1: "For Broken / Cracked Lights (Recommended)",
      description2: "Headlight OES (Price for single unit)",
      description3: "Free Pickup & Drop",
      description4: "Opening & Fitting of Bumper/Headlight",
      description5: "Projector/LEDs/DRLs Additional (If Applicable)",
      image: "/servicesimage/brake/front.jpg",
      countInStock: 20,
    },
    {
      name: "Front Brake Pads",
      description: "1 Month Warranty on Fitting",
      description1: "For Broken / Cracked Lights (Recommended)",
      description2: "Headlight OES (Price for single unit)",
      description3: "Free Pickup & Drop",
      description4: "Opening & Fitting of Bumper/Headlight",
      description5: "Projector/LEDs/DRLs Additional (If Applicable)",
      image: "/servicesimage/brake/front.jpg",
      countInStock: 20,
    },
    {
      name: "Front Brake Pads",
      description: "1 Month Warranty on Fitting",
      description1: "For Broken / Cracked Lights (Recommended)",
      description2: "Headlight OES (Price for single unit)",
      description3: "Free Pickup & Drop",
      description4: "Opening & Fitting of Bumper/Headlight",
      description5: "Projector/LEDs/DRLs Additional (If Applicable)",
      image: "/servicesimage/brake/front.jpg",
      countInStock: 20,
    },
    {
      name: "Front Brake Pads",
      description: "1 Month Warranty on Fitting",
      description1: "For Broken / Cracked Lights (Recommended)",
      description2: "Headlight OES (Price for single unit)",
      description3: "Free Pickup & Drop",
      description4: "Opening & Fitting of Bumper/Headlight",
      description5: "Projector/LEDs/DRLs Additional (If Applicable)",
      image: "/servicesimage/brake/front.jpg",
      countInStock: 20,
    },
  ],

  Steerings: [
    {
      name: "EPS Module Repair",
      description: "1 Month Warranty on Fitting",
      description1: "For Broken / Cracked Lights (Recommended)",
      description2: "Headlight OES (Price for single unit)",
      description3: "Free Pickup & Drop",
      description4: "Opening & Fitting of Bumper/Headlight",
      description5: "Projector/LEDs/DRLs Additional (If Applicable)",
      image: "/servicesimage/brake/front.jpg",
      countInStock: 20,
    },
  ],
};

export default servicedata;
